### ISSUE TITLE
Circle CCTP testnet example landing page

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/example-circle-relayer#12]
Build out Circle integration landing page including examples leveraging Wormhole & Circle CCTP.

Design: https://www.figma.com/file/SmWX2dPc7B7cpGx7QtZpiH/WH-CCTP?node-id=0%3A1

**Comment by kev1n-peters** [comment]
Here's the PR for the first stab at the new landing page https://github.com/wormhole-foundation/usdcdemo-web/pull/2 - both widgets work correctly, but the page still needs some visual changes to make it match the design.
